In [ ]:
#Importing all Libraries
import pandas as pd

In [ ]:
df = pd.read_csv("criminology_dataset (1).csv")
df

,child_id,physical_abuse,emotional_abuse,sexual_abuse,victimization,parent_monitoring,parent_support,parental_warmth,family_conflict,domestic_violence_exposure,...,drug_use,peer_delinquency,gang_exposure,household_income,parent_education,neighborhood_disadvantage,mental_health_score,impulsivity_score,criminal_risk,is_criminal
0,CHD00001,3.75,8.79,3.77,6.02,2.16,8.38,8.04,7.75,1.32,...,1.27,10.83,3.56,29297.13,3.71,5.59,9.02,2.14,46.0,0
1,CHD00002,NaN,6.34,4.82,5.55,4.61,9.45,3.86,8.39,0.24,...,2.79,14.56,9.19,116380.21,14.54,4.99,5.84,4.88,62.2,1
2,CHD00003,7.32,0.61,2.24,8.34,NaN,2.31,6.90,1.99,7.56,...,7.99,8.29,2.97,19177.79,5.53,8.41,7.65,3.29,55.9,1
3,CHD00004,5.99,9.61,4.63,5.05,0.69,5.37,4.32,6.56,5.22,...,0.19,NaN,7.40,146248.04,NaN,8.86,8.79,3.14,69.5,1
4,CHD00005,1.56,6.93,1.13,0.92,1.04,2.52,1.67,7.84,9.32,...,5.95,5.79,7.38,92131.83,17.10,9.23,3.67,0.87,58.7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,CHD14996,6.51,1.35,2.38,3.87,1.14,7.83,3.93,1.30,4.64,...,8.99,6.45,5.94,127272.79,8.64,5.59,8.86,8.33,46.1,0
14996,CHD14997,1.78,5.45,0.54,6.91,3.87,6.88,5.96,2.57,6.55,...,9.03,6.67,8.07,88258.12,5.62,5.12,1.84,3.85,41.0,0
14997,CHD14998,11.09,4.72,2.55,2.15,8.11,0.62,4.11,3.85,2.38,...,2.00,0.02,3.81,25621.89,0.57,3.54,12.13,1.12,42.5,0
14998,CHD14999,6.83,3.37,3.03,2.69,NaN,1.22,4.10,4.86,8.73,...,8.43,6.81,6.54,11282.50,13.08,8.07,12.36,2.89,54.6,1
14999,CHD15000,2.51,12.46,1.95,5.51,3.43,8.83,3.47,0.64,9.96,...,7.82,7.77,5.64,74566.54,13.37,5.35,6.71,9.26,60.2,1

Identifier

child_id — Unique ID for each child profile, formatted CHD00001 to CHD15000


Raw Abuse & Victimization (0–10)

physical_abuse — Frequency and severity of physical abuse experienced
emotional_abuse — Psychological abuse, humiliation, threats, verbal cruelty
sexual_abuse — Sexual abuse exposure (0–5, lower ceiling, rarer)
victimization — General victimization by peers, adults, or environment


Parenting Quality (0–10)

parent_monitoring — How closely parents track the child's whereabouts and activities
parent_support — Emotional and practical support provided by parents
parental_warmth — Affection, praise, and nurturing behaviour from parents


Home Environment (0–10)

family_conflict — Frequency and intensity of conflict within the household
domestic_violence_exposure — Child's direct or indirect exposure to violence between adults at home


School (0–10)

school_attendance — Regularity of attending school
school_grades — Academic performance
school_attachment — How connected and engaged the child feels at school
teacher_support — Quality of support and mentorship from teachers
school_suspensions — Number or severity of formal school suspensions


Substance Use (0–10)

alcohol_use — Frequency of alcohol consumption
smoking_frequency — Frequency of tobacco use
drug_use — Frequency of illicit drug use


Peer & Community (0–10)

peer_delinquency — Degree to which the child's peers engage in delinquent behaviour
gang_exposure — Level of exposure to gang activity in peer group or neighbourhood


Socioeconomic

household_income — Annual household income in currency units (10,000–150,000, with outliers up to 300,000)
parent_education — Years of parental education (0–20, outliers up to 25)
neighborhood_disadvantage — Level of deprivation, crime, and lack of resources in the neighbourhood (0–10)


Psychological (0–10)

mental_health_score — Overall mental wellbeing — higher is healthier
impulsivity_score — Tendency toward impulsive, unplanned behaviour — higher means more impulsive


Outcomes

criminal_risk — Continuous risk score from 0–100, derived from a weighted combination of all engineered features
is_criminal — Binary label: 1 = criminal outcome, 0 = no criminal outcome. Derived from criminal_risk with a small amount of label noise to simulate real-world uncertainty

Parent_education- age

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   child_id                    15000 non-null  object
 1   physical_abuse              14261 non-null  float64
 2   emotional_abuse             14241 non-null  float64
 3   sexual_abuse                14244 non-null  float64
 4   victimization               14245 non-null  float64
 5   parent_monitoring           14309 non-null  float64
 6   parent_support              14286 non-null  float64
 7   parental_warmth             14247 non-null  float64
 8   family_conflict             14243 non-null  float64
 9   domestic_violence_exposure  14190 non-null  float64
 10  school_attendance           14273 non-null  float64
 11  school_grades               14287 non-null  float64
 12  school_attachment           14276 non-null  float64
 13  teacher_support             14216 non-null  float64
 14  school_suspensions          14251 non-null  float64
 15  alcohol_use                 14262 non-null  float64
 16  smoking_frequency           14250 non-null  float64
 17  drug_use                    14250 non-null  float64
 18  peer_delinquency            14222 non-null  float64
 19  gang_exposure               14267 non-null  float64
 20  household_income            14098 non-null  float64
 21  parent_education            14415 non-null  float64
 22  neighborhood_disadvantage   14305 non-null  float64
 23  mental_health_score         14212 non-null  float64
 24  impulsivity_score           14256 non-null  float64
 25  criminal_risk               15000 non-null  float64
 26  is_criminal                 15000 non-null  int64
dtypes: float64(25), int64(1), object(1)
memory usage: 3.1+ MB

In [ ]:
df.describe()

,physical_abuse,emotional_abuse,sexual_abuse,victimization,parent_monitoring,parent_support,parental_warmth,family_conflict,domestic_violence_exposure,school_attendance,...,drug_use,peer_delinquency,gang_exposure,household_income,parent_education,neighborhood_disadvantage,mental_health_score,impulsivity_score,criminal_risk,is_criminal
count,14261.000000,14241.000000,14244.000000,14245.000000,14309.000000,14286.000000,14247.000000,14243.000000,14190.000000,14273.000000,...,14250.000000,14222.000000,14267.000000,14098.000000,14415.000000,14305.000000,14212.00000,14256.000000,15000.000000,15000.000000
mean,5.201611,5.196761,2.558276,5.271205,5.280870,5.223499,5.235249,5.225859,5.198827,5.257135,...,5.146105,5.255458,5.220544,84106.877475,10.320228,5.220634,5.24816,5.215186,50.504633,0.285733
std,3.126243,3.115416,1.525262,3.104077,3.142108,3.134808,3.133512,3.117601,3.128843,3.132131,...,3.130995,3.133180,3.132406,47559.973005,6.078976,3.115235,3.13276,3.106232,8.614483,0.451778
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,10009.980000,0.000000,0.000000,0.00000,0.000000,14.000000,0.000000
25%,2.540000,2.580000,1.240000,2.630000,2.610000,2.570000,2.570000,2.580000,2.550000,2.640000,...,2.470000,2.610000,2.550000,45747.092500,5.045000,2.550000,2.60000,2.590000,44.700000,0.000000
50%,5.100000,5.130000,2.550000,5.210000,5.240000,5.140000,5.210000,5.170000,5.125000,5.200000,...,5.020000,5.180000,5.200000,82159.035000,10.240000,5.170000,5.18000,5.110000,50.400000,0.000000
75%,7.720000,7.700000,3.800000,7.770000,7.820000,7.760000,7.750000,7.750000,7.680000,7.740000,...,7.630000,7.770000,7.700000,117886.495000,15.370000,7.730000,7.77000,7.730000,56.300000,1.000000
max,14.990000,15.000000,7.500000,14.980000,15.000000,14.990000,15.000000,14.990000,15.000000,15.000000,...,15.000000,14.980000,14.990000,299791.110000,24.980000,15.000000,14.99000,14.980000,83.300000,1.000000

In [ ]:
df.isna().sum()

child_id                        0
physical_abuse                739
emotional_abuse               759
sexual_abuse                  756
victimization                 755
parent_monitoring             691
parent_support                714
parental_warmth               753
family_conflict               757
domestic_violence_exposure    810
school_attendance             727
school_grades                 713
school_attachment             724
teacher_support               784
school_suspensions            749
alcohol_use                   738
smoking_frequency             750
drug_use                      750
peer_delinquency              778
gang_exposure                 733
household_income              902
parent_education              585
neighborhood_disadvantage     695
mental_health_score           788
impulsivity_score             744
criminal_risk                   0
is_criminal                     0
dtype: int64

In [ ]:
target = [
    "physical_abuse", "emotional_abuse", "school_grades", "school_attachment", 
    "teacher_support", "school_suspensions", "alcohol_use", "smoking_frequency", 
    "sexual_abuse", "victimization", "parent_monitoring", "parent_support", 
    "parental_warmth", "family_conflict", "domestic_violence_exposure", 
    "school_attendance", "drug_use", "peer_delinquency", "gang_exposure", 
    "household_income", "parent_education", "neighborhood_disadvantage", 
    "mental_health_score", "impulsivity_score"
]
df[target] = df[target].fillna(df[target].mean())

In [ ]:
df.isna().sum()

child_id                      0
physical_abuse                0
emotional_abuse               0
sexual_abuse                  0
victimization                 0
parent_monitoring             0
parent_support                0
parental_warmth               0
family_conflict               0
domestic_violence_exposure    0
school_attendance             0
school_grades                 0
school_attachment             0
teacher_support               0
school_suspensions            0
alcohol_use                   0
smoking_frequency             0
drug_use                      0
peer_delinquency              0
gang_exposure                 0
household_income              0
parent_education              0
neighborhood_disadvantage     0
mental_health_score           0
impulsivity_score             0
criminal_risk                 0
is_criminal                   0
dtype: int64

In [ ]:
df.head()

,child_id,physical_abuse,emotional_abuse,sexual_abuse,victimization,parent_monitoring,parent_support,parental_warmth,family_conflict,domestic_violence_exposure,...,drug_use,peer_delinquency,gang_exposure,household_income,parent_education,neighborhood_disadvantage,mental_health_score,impulsivity_score,criminal_risk,is_criminal
0,CHD00001,3.750000,8.79,3.77,6.02,2.16000,8.38,8.04,7.75,1.32,...,1.27,10.830000,3.56,29297.13,3.710000,5.59,9.02,2.14,46.0,0
1,CHD00002,5.201611,6.34,4.82,5.55,4.61000,9.45,3.86,8.39,0.24,...,2.79,14.560000,9.19,116380.21,14.540000,4.99,5.84,4.88,62.2,1
2,CHD00003,7.320000,0.61,2.24,8.34,5.28087,2.31,6.90,1.99,7.56,...,7.99,8.290000,2.97,19177.79,5.530000,8.41,7.65,3.29,55.9,1
3,CHD00004,5.990000,9.61,4.63,5.05,0.69000,5.37,4.32,6.56,5.22,...,0.19,5.255458,7.40,146248.04,10.320228,8.86,8.79,3.14,69.5,1
4,CHD00005,1.560000,6.93,1.13,0.92,1.04000,2.52,1.67,7.84,9.32,...,5.95,5.790000,7.38,92131.83,17.100000,9.23,3.67,0.87,58.7,1

In [ ]:
#Feature Engineering 
df["abuse"]= (df["physical_abuse"] + df["emotional_abuse"]+df["sexual_abuse"]+df["victimization"])
df["parental_neglect"] = (30 - df["parent_monitoring"]- df["parent_support"]-df["parental_warmth"])
df["school_neglect"] = (40- df["school_attendance"] - df["school_grades"] - df["school_attachment"] - df["teacher_support"] - df["school_suspensions"])
df["substance_exposure"] = (df["alcohol_use"] + df["smoking_frequency"] + df["drug_use"])
df["household_instability"] = (df["family_conflict"] + df["domestic_violence_exposure"] + df["neighborhood_disadvantage"])

In [ ]:
X = df[["abuse","parental_neglect","school_neglect","substance_exposure","household_instability","peer_delinquency","impulsivity_score","mental_health_score"]]

y = df["is_criminal"]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state = 42)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 10)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [ ]:
from sklearn.metrics import accuracy_score
pred = knn.predict(X_test)
print(accuracy_score(y_test, pred))

0.7803333333333333

Since accuracy is 78 percent we can notice that the dataset was based on real_life information, noise exists in the dataset just like real dataset.
The Syntethic dataset mimics a realworld dataset.

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

[[2027  125]
 [ 534  314]]
              precision    recall  f1-score   support

           0       0.79      0.94      0.86      2152
           1       0.72      0.37      0.49       848

    accuracy                           0.78      3000
   macro avg       0.75      0.66      0.67      3000
weighted avg       0.77      0.78      0.75      3000

In [ ]:
import joblib

joblib.dump(knn, "knn_model.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']

In [ ]:
scores = []

for k in range(1,21):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train)

    pred = knn.predict(X_test)

    scores.append(accuracy_score(y_test,pred))

In [ ]:
print(scores)

[0.7066666666666667, 0.7413333333333333, 0.7416666666666667, 0.7623333333333333, 0.7576666666666667, 0.7656666666666667, 0.7693333333333333, 0.774, 0.78, 0.7803333333333333, 0.7756666666666666, 0.778, 0.78, 0.7803333333333333, 0.7806666666666666, 0.782, 0.7823333333333333, 0.7803333333333333, 0.7833333333333333, 0.7796666666666666]

In [ ]:
player = {
    "abuse": 0,
    "parental_neglect": 0,
    "school_neglect": 0,
    "substance_exposure": 0,
    "household_instability": 0,
    "peer_delinquency": 0,
    "impulsivity_score": 0,
    "mental_health_score": 0
}